### ISSUE TITLE
Cannot access admin panel

### ISSUE THREAD

**Issue by kartik2318** [M45um19/Dynamic-News-portal-Site#1]
I am unable to access admin panel, as it is showing Username or Password don't match. (Although I have entered the correct credientials)

**Comment by M45um19** [comment]
@kartik2318 Please download the project again and use the updated database. username: admin, password: admin

**Comment by kartik2318** [comment]
> @kartik2318 Please download the project again and use the updated database. username: admin, password: admin

Updated Database..?? Which one, because now there is no Database folder...

**Comment by kartik2318** [comment]
> @kartik2318 Please download the project again and use the updated database. username: admin, password: admin

Sorted.. Sorted.. Thanks..😀

**Comment by kartik2318** [comment]
> @kartik2318 Please download the project again and use the updated database. username: admin, password: admin

Sorted.. Sorted.. Thanks..😀
